version: '2.2'

services:
  task:
    build: ./task
    image: alexei2ru/tasksampleapp
    ports:
      - 8080:8080
      - 9009:9009
    environment:
      - DB_SERVER=task-db
      - DB_USER=dbuser
      - DB_PASSWORD=dbpassword
    depends_on:
      - task-db
  task-db:
    build: ./task-db
    image: alexei2ru/tasksampleapp
    ports:
      - 5432:5432
