apiVersion: v1
kind: Service
metadata:
  name: task-service
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 30080
      targetPort: 8080
  selector:
    app: task

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-deployment
  labels:
    app: task
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task
  template:
    metadata:
      labels:
        app: task
    spec:
      containers:
      - name: task-db
        image: alexei2ru/tasksampledb:test
        ports:
        - containerPort: 5432
        env: 
        - name: POSTGRES_HOST_AUTH_METHOD
          value: trust
      - name: task-app
        image: alexei2ru/tasksampleapp:test
        ports:
          - containerPort: 8080
          - containerPort: 9009
        env:
          - name: DB_PASSWORD
            value: dbpassword
          - name: DB_SERVER
            value: task-db
          - name: DB_USER
            value: dbuser
      restartPolicy: Always