apiVersion: v1
kind: Service
metadata:
  name: task-app-service
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 30080
    nodePort: 30080
    targetPort: 8080
  selector:
    app: task-app

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-app-deployment
  labels:
    app: task-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-app
  template:
    metadata:
      labels:
        app: task-app
    spec:
      containers:
      - env:
        - name: DB_PASSWORD
          value: dbpassword
        - name: DB_SERVER
          value: task-db
        - name: DB_USER
          value: dbuser
        name: task-app
        image: alexei2ru/tasksampleapp:test
        ports:
        - containerPort: 8080
        - containerPort: 9009
      restartPolicy: Always
status: {}
