apiVersion: v1
kind: Service
metadata:
  name: task-db-service
spec:
  type: NodePort
  selector:
    app: task-db
  ports:
    - protocol: TCP
      port: 15432
      nodePort: 5432
  status:
    loadBalancer: {}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-db-deployment
  labels:
    app: task-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-db
  template:
    metadata:
      labels:
        app: task-db
    spec:
      containers:
      - name: task-db
        image: alexei2ru/tasksampledb:test
        ports:
        - containerPort: 5432
        env: 
        - name: POSTGRES_HOST_AUTH_METHOD
          value: trust
      restartPolicy: Always
    resources: {}