apiVersion: v1
kind: Service
metadata:
  name: task-db-service
spec:
  selector:
    app: task-db
  ports:
    - protocol: TCP
      port: 15432
      targetPort: 5432

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-db-deployment
  labels:
    app: task-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-db
  template:
    metadata:
      labels:
        app: task-db
    spec:
      containers:
      - name: task-db-test
        image: alexei2ru/tasksampledb:test
        ports:
        - containerPort: 5432
      restartPolicy: Always