apiVersion: v1
kind: Service
metadata:
  name: task-db-service
spec:
  ports:
    port: 15432
    targetPort: 5432
  selector:
    app: task-db
status:
  loadBalancer: {}

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: task-db-deployment
  labels:
    app: task-db
spec:
  replicas: 1
  selector:
    matchlabels:
      app: task-db
  template:
    metadata:
      labels:
        app: task-db
    spec:
      containers:
      - env:
        - name: POSTGRES_HOST_AUTH_METHOD
          value: trust
        image: alexei2ru/tasksampledb:test
        name: task-db-test
        ports:
        - containerPort: 5432
        resources: {}
      restartPolicy: Always